#!/usr/bin/env bash
# Install, migrate, inspect, or roll back Dreaming LaunchAgents.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DREAMING_REPO_ROOT="${DREAMING_REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd -P)}"
DREAMING_CONFIG_FILE="${DREAMING_CONFIG_FILE:-$HOME/.copilot/dreaming/config.env}"
DREAMING_DEPS_DIR="${DREAMING_DEPS_DIR:-$HOME/.copilot/dreaming/deps}"
DEST_DIR="${SKILLS_LAUNCH_AGENTS_DIR:-$HOME/Library/LaunchAgents}"
STATE_DIR="${SKILLS_STATE_DIR:-$HOME/.copilot/skill-state}"
LOCAL_ROOT="${SKILLS_LOCAL_ROOT:-$HOME/.copilot/skills}"
DOMAIN="${SKILLS_LAUNCHD_DOMAIN:-gui/$(id -u)}"
LAUNCHCTL="${LAUNCHCTL_BIN:-launchctl}"
COPILOT="${COPILOT_BIN:-$HOME/.local/bin/copilot}"
COPILOT_ROOT="${COPILOT_HOME:-$HOME/.copilot}"
NEW_PREFIX="${DREAMING_LAUNCHD_PREFIX:-com.${USER}.dreaming}"
LEGACY_PREFIX="${SKILLS_LAUNCHD_PREFIX:-com.${USER}.skills}"
HALT_SWITCH="$STATE_DIR/skill-review/disable-daemon"
BACKUP_POINTER="$STATE_DIR/dreaming/latest-migration-backup"
ACTIVE_PREPARE_FILE="$STATE_DIR/dreaming/active-migration-backup"
GENERATION_FILE="$STATE_DIR/dreaming/activation-generation"
SELFTEST_GENERATION_FILE="$STATE_DIR/dreaming/selftest-passed-generation"
SELFTEST_LABEL_FILE="$STATE_DIR/dreaming/active-selftest-label"
NEW_KINDS=(dreaming selftest watchdog)
LEGACY_KINDS=(sweep curator memory selftest watchdog dreaming)

[[ "$NEW_PREFIX" =~ ^[A-Za-z0-9._-]+$ &&
   "$LEGACY_PREFIX" =~ ^[A-Za-z0-9._-]+$ ]] || {
  echo "launchd label prefixes may contain only letters, digits, dot, underscore, and hyphen" >&2
  exit 2
}

label_for() { printf '%s.%s\n' "$1" "$2"; }

all_labels() {
  local kind
  for kind in "${NEW_KINDS[@]}"; do label_for "$NEW_PREFIX" "$kind"; done
  for kind in "${LEGACY_KINDS[@]}"; do label_for "$LEGACY_PREFIX" "$kind"; done
}

bootout_label() {
  "$LAUNCHCTL" bootout "$DOMAIN/$1" >/dev/null 2>&1 || true
}

atomic_pointer() {
  local value="$1" target="$2" temporary
  mkdir -p "$(dirname "$target")"
  temporary="$(dirname "$target")/.${target##*/}.$$"
  printf '%s\n' "$value" > "$temporary"
  mv -f "$temporary" "$target"
}

activate_halt() {
  mkdir -p "$STATE_DIR/skill-review" "$STATE_DIR/dreaming"
  touch "$HALT_SWITCH"
}

cmd_prepare() {
  local label source backup stamp copied=0
  mkdir -p "$DEST_DIR" "$STATE_DIR/dreaming/migration-backups"
  activate_halt

  if [[ -f "$ACTIVE_PREPARE_FILE" ]] &&
      backup="$(<"$ACTIVE_PREPARE_FILE")" &&
      [[ -d "$backup" && -f "$backup/.dreaming-backup-complete" ]]; then
    :
  else
    stamp="$(date -u +%Y%m%dT%H%M%SZ)-$$"
    backup="$STATE_DIR/dreaming/migration-backups/$stamp"
    mkdir -p "$backup"
    while IFS= read -r label; do
      source="$DEST_DIR/$label.plist"
      if [[ -f "$source" ]]; then
        cp -p "$source" "$backup/"
        copied=$((copied + 1))
      fi
    done < <(all_labels | awk '!seen[$0]++')
    printf '%s\n' "$copied" > "$backup/.plist-count"
    touch "$backup/.dreaming-backup-complete"
    atomic_pointer "$backup" "$BACKUP_POINTER"
    atomic_pointer "$backup" "$ACTIVE_PREPARE_FILE"
  fi

  while IFS= read -r label; do
    bootout_label "$label"
  done < <(all_labels | awk '!seen[$0]++')
  echo "prepared migration behind halt; rollback backup: $backup"
}

load_config() {
  [[ -f "$DREAMING_CONFIG_FILE" ]] || {
    echo "dependency config missing: $DREAMING_CONFIG_FILE" >&2
    return 1
  }
  # Generated by dreaming-deps.py using shell-quoted scalar assignments.
  # shellcheck disable=SC1090
  source "$DREAMING_CONFIG_FILE"
  export DREAMING_REPO_ROOT DREAMING_SHARED_SKILLS_ROOT
  export SKILLS_REPO_ROOT="${SKILLS_REPO_ROOT:-}"
}

render() {
  local kind="$1" label destination template
  label="$(label_for "$NEW_PREFIX" "$kind")"
  template="$DREAMING_REPO_ROOT/skills/skill-review/assets/launchd/$kind.plist.tpl"
  destination="$DEST_DIR/$label.plist"
  /usr/bin/python3 - "$template" "$destination" "$label" "$HOME" \
    "$DREAMING_REPO_ROOT" "$DREAMING_SHARED_SKILLS_ROOT" \
    "${SKILLS_REPO_ROOT:-}" "$STATE_DIR" "$LOCAL_ROOT" "$COPILOT_ROOT" <<'PY'
import html
import sys

template, destination, label, home, repo, shared, public, state, local, copilot_home = sys.argv[1:]
text = open(template, encoding="utf-8").read()
replacements = {
    "__LABEL__": label,
    "__HOME__": home,
    "__DREAMING_REPO_ROOT__": repo,
    "__DREAMING_SHARED_SKILLS_ROOT__": shared,
    "__SKILLS_STATE_DIR__": state,
    "__SKILLS_LOCAL_ROOT__": local,
    "__COPILOT_HOME__": copilot_home,
}
for key, value in replacements.items():
    text = text.replace(key, html.escape(value))
public_env = ""
if public:
    public_env = (
        "    <key>SKILLS_REPO_ROOT</key><string>"
        + html.escape(public)
        + "</string>\n"
    )
text = text.replace("__SKILLS_REPO_ROOT_ENV__", public_env)
with open(destination, "w", encoding="utf-8") as handle:
    handle.write(text)
PY
  /usr/bin/plutil -lint "$destination" >/dev/null
}

sync_plugin() {
  [[ "${DREAMING_SKIP_PLUGIN_SYNC:-0}" == "1" ]] && return 0
  [[ -x "$COPILOT" ]] || {
    echo "copilot is not executable at $COPILOT" >&2
    return 1
  }
  "$COPILOT" plugin update dfrysinger-dreaming >/dev/null 2>&1 ||
    "$COPILOT" plugin install dfrysinger/dreaming
}

cmd_install() {
  local kind label generation
  cmd_prepare
  DREAMING_REPO_ROOT="$DREAMING_REPO_ROOT" \
    DREAMING_DEPS_DIR="$DREAMING_DEPS_DIR" \
    DREAMING_CONFIG_FILE="$DREAMING_CONFIG_FILE" \
    "$DREAMING_REPO_ROOT/scripts/dreaming-deps.py" materialize
  load_config
  sync_plugin
  chmod +x "$DREAMING_REPO_ROOT/scripts/"*.sh \
    "$DREAMING_REPO_ROOT/scripts/"*.py \
    "$DREAMING_REPO_ROOT"/skills/*/scripts/*.sh \
    "$DREAMING_REPO_ROOT"/skills/*/scripts/*.py 2>/dev/null || true
  "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" install

  for kind in "${LEGACY_KINDS[@]}"; do
    label="$(label_for "$LEGACY_PREFIX" "$kind")"
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done
  for kind in "${NEW_KINDS[@]}"; do
    label="$(label_for "$NEW_PREFIX" "$kind")"
    render "$kind"
    "$LAUNCHCTL" bootstrap "$DOMAIN" "$DEST_DIR/$label.plist"
    "$LAUNCHCTL" enable "$DOMAIN/$label" >/dev/null 2>&1 || true
    echo "loaded $label"
  done
  generation="$(date -u +%Y%m%dT%H%M%SZ)-install-$$"
  atomic_pointer "$generation" "$GENERATION_FILE"
  atomic_pointer "$(label_for "$NEW_PREFIX" selftest)" "$SELFTEST_LABEL_FILE"
  rm -f "$SELFTEST_GENERATION_FILE"
  echo "installed ${#NEW_KINDS[@]} agents; halt remains active until selftest and enable"
}

cmd_selftest() {
  local label result wait_secs waited generation
  [[ -f "$SELFTEST_LABEL_FILE" ]] || {
    echo "no active selftest label; run install or rollback first" >&2
    return 1
  }
  label="$(<"$SELFTEST_LABEL_FILE")"
  result="${DREAMING_SELFTEST_RESULT_FILE:-$STATE_DIR/daemon-selftest.out}"
  wait_secs="${DREAMING_SELFTEST_WAIT_SECS:-120}"
  [[ -f "$GENERATION_FILE" ]] || {
    echo "no activation generation; run install or rollback first" >&2
    return 1
  }
  rm -f "$result"
  "$LAUNCHCTL" kickstart -k "$DOMAIN/$label" >/dev/null 2>&1 || {
    echo "selftest agent not loaded; run install first" >&2
    return 1
  }
  waited=0
  while (( waited < wait_secs )); do
    if [[ -f "$result" ]] && grep -q '^== result: [0-9][0-9]* failure(s) ==$' "$result"; then
      break
    fi
    sleep 1
    waited=$((waited + 1))
  done
  [[ -f "$result" ]] || { echo "selftest produced no result file" >&2; return 1; }
  cat "$result"
  grep -q '^== result: 0 failure(s) ==$' "$result" || {
    echo "selftest did not pass" >&2
    return 1
  }
  generation="$(<"$GENERATION_FILE")"
  atomic_pointer "$generation" "$SELFTEST_GENERATION_FILE"
  echo "selftest passed for activation generation $generation"
}

cmd_enable() {
  local generation passed
  [[ -f "$GENERATION_FILE" && -f "$SELFTEST_GENERATION_FILE" ]] || {
    echo "current activation has not passed selftest" >&2
    return 1
  }
  generation="$(<"$GENERATION_FILE")"
  passed="$(<"$SELFTEST_GENERATION_FILE")"
  [[ "$generation" == "$passed" ]] || {
    echo "selftest belongs to a different activation generation" >&2
    return 1
  }
  rm -f "$HALT_SWITCH"
  rm -f "$ACTIVE_PREPARE_FILE"
  echo "dreaming enabled"
}

cmd_status() {
  local label
  echo "halt=$([[ -e "$HALT_SWITCH" ]] && echo active || echo inactive)"
  [[ -f "$BACKUP_POINTER" ]] && echo "rollback_backup=$(<"$BACKUP_POINTER")"
  [[ -f "$GENERATION_FILE" ]] && echo "activation_generation=$(<"$GENERATION_FILE")"
  "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" status || true
  while IFS= read -r label; do
    echo "--- $label ---"
    "$LAUNCHCTL" print "$DOMAIN/$label" 2>/dev/null |
      grep -E 'state|runs|last exit|program =' || echo "  (not loaded)"
  done < <(all_labels | awk '!seen[$0]++')
}

cmd_uninstall() {
  local label
  cmd_prepare
  while IFS= read -r label; do
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done < <(all_labels | awk '!seen[$0]++')
  rm -f "$GENERATION_FILE" "$SELFTEST_GENERATION_FILE" "$SELFTEST_LABEL_FILE"
  "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" uninstall
  echo "uninstalled all known dreaming and legacy agents; halt remains active"
}

verify_backup() {
  /usr/bin/python3 - "$1" <<'PY'
import os
import plistlib
import sys
from pathlib import Path

backup = Path(sys.argv[1])
plists = sorted(backup.glob("*.plist"))
if not plists:
    raise SystemExit("backup contains no LaunchAgent plists")
failures = []
for plist in plists:
    try:
        data = plistlib.loads(plist.read_bytes())
    except Exception as exc:
        failures.append(f"{plist.name}: malformed plist: {exc}")
        continue
    arguments = data.get("ProgramArguments")
    if not isinstance(arguments, list) or not arguments or not all(
        isinstance(value, str) for value in arguments
    ):
        failures.append(f"{plist.name}: ProgramArguments must be a non-empty string array")
        continue
    for index, raw in enumerate(arguments):
        path = Path(os.path.expanduser(raw))
        if not path.is_absolute():
            continue
        must_execute = index == 0 or path.suffix in {".sh", ".py"} or os.access(path, os.X_OK)
        if must_execute and not (path.is_file() and os.access(path, os.X_OK)):
            failures.append(f"{plist.name}: executable missing or not executable: {path}")
        elif not must_execute and not path.exists():
            failures.append(f"{plist.name}: durable argument path is missing: {path}")
if failures:
    raise SystemExit("\n".join(failures))
PY
}

cmd_rollback() {
  local backup="${1:-}" label plist generation lock_path selftest_plist
  activate_halt
  if [[ -z "$backup" ]]; then
    [[ -f "$BACKUP_POINTER" ]] || {
      echo "no migration backup recorded" >&2
      return 1
    }
    backup="$(<"$BACKUP_POINTER")"
  fi
  [[ -d "$backup" && -f "$backup/.dreaming-backup-complete" ]] || {
    echo "invalid migration backup: $backup" >&2
    return 1
  }
  verify_backup "$backup"
  selftest_plist="$(find "$backup" -maxdepth 1 -type f -name '*.selftest.plist' -print)"
  [[ -n "$selftest_plist" && "$(printf '%s\n' "$selftest_plist" | wc -l | tr -d ' ')" == "1" ]] || {
    echo "rollback backup must contain exactly one selftest LaunchAgent" >&2
    return 1
  }

  while IFS= read -r label; do
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done < <(all_labels | awk '!seen[$0]++')
  lock_path="$STATE_DIR/daemon.lock"
  if [[ -f "$lock_path" ]]; then
    mv "$lock_path" "$STATE_DIR/dreaming/daemon.lock.sqlite-before-rollback"
    [[ -f "${lock_path}-wal" ]] &&
      mv "${lock_path}-wal" "$STATE_DIR/dreaming/daemon.lock.sqlite-wal-before-rollback"
    [[ -f "${lock_path}-shm" ]] &&
      mv "${lock_path}-shm" "$STATE_DIR/dreaming/daemon.lock.sqlite-shm-before-rollback"
  fi
  for plist in "$backup"/*.plist; do
    [[ -e "$plist" ]] || continue
    cp -p "$plist" "$DEST_DIR/"
    label="$(basename "$plist" .plist)"
    "$LAUNCHCTL" bootstrap "$DOMAIN" "$DEST_DIR/$label.plist"
    "$LAUNCHCTL" enable "$DOMAIN/$label" >/dev/null 2>&1 || true
    echo "restored $label"
  done
  generation="$(date -u +%Y%m%dT%H%M%SZ)-rollback-$$"
  atomic_pointer "$generation" "$GENERATION_FILE"
  atomic_pointer "$(basename "$selftest_plist" .plist)" "$SELFTEST_LABEL_FILE"
  rm -f "$SELFTEST_GENERATION_FILE"
  echo "rollback loaded behind halt from $backup; run restored selftest, then enable explicitly"
}

case "${1:-}" in
  prepare) cmd_prepare ;;
  install) cmd_install ;;
  selftest) cmd_selftest ;;
  enable) cmd_enable ;;
  status) cmd_status ;;
  uninstall) cmd_uninstall ;;
  rollback) shift; cmd_rollback "${1:-}" ;;
  *)
    echo "usage: scripts/install.sh {prepare|install|selftest|enable|status|uninstall|rollback [backup]}" >&2
    exit 2
    ;;
esac
