#!/usr/bin/env bash
# Install, migrate, inspect, or roll back Dreaming LaunchAgents.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
REQUESTED_REPO_ROOT="${DREAMING_REPO_ROOT:-}"
DREAMING_REPO_ROOT="${REQUESTED_REPO_ROOT:-$DEFAULT_REPO_ROOT}"
REQUESTED_DATA_DIR="${DREAMING_DATA_DIR:-}"
REQUESTED_STATE_DIR="${DREAMING_STATE_DIR:-}"
REQUESTED_SKILLS_ROOT="${DREAMING_SKILLS_ROOT:-}"
REQUESTED_DEPS_DIR="${DREAMING_DEPS_DIR:-}"
REQUESTED_ADAPTER_CONFIG="${DREAMING_ADAPTER_CONFIG:-}"
if [[ -n "${DREAMING_INSTALLER_CALLER_ADAPTER_CONFIG_EXPLICIT+x}" ]]; then
  REQUESTED_ADAPTER_CONFIG_EXPLICIT="$DREAMING_INSTALLER_CALLER_ADAPTER_CONFIG_EXPLICIT"
else
  REQUESTED_ADAPTER_CONFIG_EXPLICIT=$([[ -n "$REQUESTED_ADAPTER_CONFIG" ]] && echo 1 || echo 0)
fi
if [[ "$REQUESTED_ADAPTER_CONFIG_EXPLICIT" == "0" ]]; then
  REQUESTED_ADAPTER_CONFIG=""
fi
REQUESTED_COPILOT_COMPAT="${DREAMING_ENABLE_COPILOT_COMPAT:-}"
REQUESTED_CONFIG_FILE="${DREAMING_CONFIG_FILE:-}"
REQUESTED_RECEIPT_FILE="${DREAMING_RECEIPT_FILE:-}"
REQUESTED_NATIVE_ADAPTERS="${DREAMING_CONFIGURE_NATIVE_ADAPTERS:-}"
REQUESTED_COPILOT_MIGRATION="${DREAMING_MIGRATE_COPILOT:-0}"
if [[ -n "${DREAMING_INSTALLER_CALLER_ADAPTER_DESIRED_STATE+x}" ]]; then
  REQUESTED_ADAPTER_DESIRED_STATE="$DREAMING_INSTALLER_CALLER_ADAPTER_DESIRED_STATE"
else
  REQUESTED_ADAPTER_DESIRED_STATE=0
  if [[ "$REQUESTED_NATIVE_ADAPTERS" == "1" ||
        -n "${DREAMING_SESSION_SOURCES+x}" ||
        -n "${DREAMING_REVIEW_EXECUTORS+x}" ||
        -n "${DREAMING_SKILL_TARGETS+x}" ||
        -n "${DREAMING_SOURCE_EXECUTOR_ALLOW+x}" ||
        -n "${DREAMING_QUIET_SECONDS+x}" ||
        -n "${DREAMING_COPILOT_SESSION_ROOT+x}" ||
        -n "${DREAMING_CLAUDE_SESSION_ROOT+x}" ||
        -n "${DREAMING_CODEX_SESSION_ROOT+x}" ||
        -n "${DREAMING_COPILOT_QUIET_SECONDS+x}" ||
        -n "${DREAMING_CLAUDE_QUIET_SECONDS+x}" ||
        -n "${DREAMING_CODEX_QUIET_SECONDS+x}" ||
        -n "${DREAMING_EXECUTOR_TIMEOUT+x}" ||
        -n "${DREAMING_COPILOT_EXECUTOR_TIMEOUT+x}" ||
        -n "${DREAMING_CLAUDE_EXECUTOR_TIMEOUT+x}" ||
        -n "${DREAMING_CODEX_EXECUTOR_TIMEOUT+x}" ]]; then
    REQUESTED_ADAPTER_DESIRED_STATE=1
  fi
fi
export DREAMING_INSTALLER_CALLER_ADAPTER_CONFIG_EXPLICIT="$REQUESTED_ADAPTER_CONFIG_EXPLICIT"
export DREAMING_INSTALLER_CALLER_ADAPTER_DESIRED_STATE="$REQUESTED_ADAPTER_DESIRED_STATE"
DEFAULT_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dreaming"
DREAMING_CONFIG_POINTER="${DREAMING_CONFIG_POINTER:-${XDG_CONFIG_HOME:-$HOME/.config}/dreaming/active-config}"
if [[ -n "$REQUESTED_CONFIG_FILE" ]]; then
  DREAMING_CONFIG_FILE="$REQUESTED_CONFIG_FILE"
elif [[ -f "$DREAMING_CONFIG_POINTER" ]]; then
  DREAMING_CONFIG_FILE="$(<"$DREAMING_CONFIG_POINTER")"
  [[ "$DREAMING_CONFIG_FILE" == /* ]] || {
    echo "Dreaming config pointer is not absolute: $DREAMING_CONFIG_POINTER" >&2
    exit 1
  }
  [[ -f "$DREAMING_CONFIG_FILE" ]] || {
    echo "Dreaming config pointer target is missing: $DREAMING_CONFIG_FILE" >&2
    exit 1
  }
else
  DREAMING_CONFIG_FILE="${REQUESTED_DATA_DIR:-$DEFAULT_DATA_DIR}/config.env"
fi
RESOLVED_CONFIG_FILE="$DREAMING_CONFIG_FILE"
if [[ -f "$DREAMING_CONFIG_FILE" ]]; then
  # Generated by dreaming-deps.py using shell-quoted scalar assignments.
  # shellcheck disable=SC1090
  source "$DREAMING_CONFIG_FILE"
fi
DREAMING_CONFIG_FILE="$RESOLVED_CONFIG_FILE"
DREAMING_DATA_DIR="${REQUESTED_DATA_DIR:-${DREAMING_DATA_DIR:-$DEFAULT_DATA_DIR}}"
DREAMING_STATE_DIR="${REQUESTED_STATE_DIR:-${DREAMING_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/dreaming}}"
DREAMING_SKILLS_ROOT="${REQUESTED_SKILLS_ROOT:-${DREAMING_SKILLS_ROOT:-$DREAMING_DATA_DIR/skills}}"
DREAMING_DEPS_DIR="${REQUESTED_DEPS_DIR:-${DREAMING_DEPS_DIR:-$DREAMING_DATA_DIR/deps}}"
DREAMING_ADAPTER_CONFIG="${REQUESTED_ADAPTER_CONFIG:-${DREAMING_ADAPTER_CONFIG:-}}"
DREAMING_ENABLE_COPILOT_COMPAT="${REQUESTED_COPILOT_COMPAT:-${DREAMING_ENABLE_COPILOT_COMPAT:-1}}"
DREAMING_REPO_ROOT="${REQUESTED_REPO_ROOT:-${DREAMING_REPO_ROOT:-$DEFAULT_REPO_ROOT}}"
DREAMING_RECEIPT_FILE="${REQUESTED_RECEIPT_FILE:-${DREAMING_RECEIPT_FILE:-}}"
DREAMING_DASHBOARD_HOST="${DREAMING_DASHBOARD_HOST:-127.0.0.1}"
DREAMING_DASHBOARD_PORT="${DREAMING_DASHBOARD_PORT:-47673}"
[[ "$DREAMING_DASHBOARD_HOST" == "127.0.0.1" ]] || {
  echo "DREAMING_DASHBOARD_HOST must be 127.0.0.1" >&2
  exit 2
}
[[ "$DREAMING_DASHBOARD_PORT" =~ ^[0-9]+$ ]] &&
  (( 10#$DREAMING_DASHBOARD_PORT >= 1 &&
     10#$DREAMING_DASHBOARD_PORT <= 65535 )) || {
  echo "DREAMING_DASHBOARD_PORT must be an integer from 1 through 65535" >&2
  exit 2
}
if [[ -n "${DREAMING_RECEIPT_FILE:-}" ]]; then
  export DREAMING_RECEIPT_FILE
else
  unset DREAMING_RECEIPT_FILE
fi
DEST_DIR="${SKILLS_LAUNCH_AGENTS_DIR:-$HOME/Library/LaunchAgents}"
if [[ -n "${SKILLS_STATE_DIR:-}" ]]; then
  STATE_DIR="$SKILLS_STATE_DIR"
elif [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
  STATE_DIR="$HOME/.copilot/skill-state"
else
  STATE_DIR="$DREAMING_STATE_DIR"
fi
if [[ -n "${SKILLS_LOCAL_ROOT:-}" ]]; then
  LOCAL_ROOT="$SKILLS_LOCAL_ROOT"
elif [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
  LOCAL_ROOT="$HOME/.copilot/skills"
else
  LOCAL_ROOT="$DREAMING_SKILLS_ROOT"
fi
if [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
  DREAMING_ORCHESTRATOR_STATE_DIR="${DREAMING_ORCHESTRATOR_STATE_DIR:-$STATE_DIR/dreaming}"
else
  DREAMING_ORCHESTRATOR_STATE_DIR="${DREAMING_ORCHESTRATOR_STATE_DIR:-$DREAMING_STATE_DIR/orchestrator}"
fi

export_runtime_env() {
  export DREAMING_REPO_ROOT DREAMING_SHARED_SKILLS_ROOT DREAMING_DATA_DIR
  export DREAMING_STATE_DIR DREAMING_SKILLS_ROOT DREAMING_DEPS_DIR
  export DREAMING_ADAPTER_CONFIG DREAMING_ENABLE_COPILOT_COMPAT
  export DREAMING_CONFIG_FILE DREAMING_CONFIG_POINTER DREAMING_RECEIPT_FILE
  export DREAMING_SHARED_BUNDLE_ID DREAMING_SHARED_SOURCE_KIND
  export DREAMING_SHARED_PROTOCOL DREAMING_SHARED_REVISION
  export DREAMING_ORCHESTRATOR_STATE_DIR
  export DREAMING_DASHBOARD_HOST DREAMING_DASHBOARD_PORT
  export SKILLS_REPO_ROOT="${SKILLS_REPO_ROOT:-}"
}

export_runtime_env

DOMAIN="${SKILLS_LAUNCHD_DOMAIN:-gui/$(id -u)}"
LAUNCHCTL="${LAUNCHCTL_BIN:-launchctl}"
COPILOT="${COPILOT_BIN:-$HOME/.local/bin/copilot}"
COPILOT_ROOT="${COPILOT_HOME:-$HOME/.copilot}"
NEW_PREFIX="${DREAMING_LAUNCHD_PREFIX:-com.${USER}.dreaming}"
LEGACY_PREFIX="${SKILLS_LAUNCHD_PREFIX:-com.${USER}.skills}"
HALT_SWITCH="$STATE_DIR/skill-review/disable-daemon"
BACKUP_POINTER="$STATE_DIR/dreaming/latest-migration-backup"
ACTIVE_PREPARE_FILE="$STATE_DIR/dreaming/active-migration-backup"
GENERATION_FILE="$STATE_DIR/dreaming/activation-generation"
SELFTEST_GENERATION_FILE="$STATE_DIR/dreaming/selftest-passed-generation"
SELFTEST_LABEL_FILE="$STATE_DIR/dreaming/active-selftest-label"
LIFECYCLE_LOCK_FILE="$STATE_DIR/dreaming/lifecycle.lock"
DASHBOARD_TOKEN_FILE="${DREAMING_DASHBOARD_TOKEN_FILE:-$DREAMING_STATE_DIR/dashboard/access-token}"
DASHBOARD_ASSETS="$DREAMING_REPO_ROOT/skills/skill-review/assets/dashboard"
NEW_KINDS=(dreaming selftest watchdog dashboard)
LEGACY_KINDS=(sweep curator memory selftest watchdog dreaming dashboard)

[[ "$NEW_PREFIX" =~ ^[A-Za-z0-9._-]+$ &&
   "$LEGACY_PREFIX" =~ ^[A-Za-z0-9._-]+$ ]] || {
  echo "launchd label prefixes may contain only letters, digits, dot, underscore, and hyphen" >&2
  exit 2
}

label_for() { printf '%s.%s\n' "$1" "$2"; }

all_labels() {
  local kind
  for kind in "${NEW_KINDS[@]}"; do label_for "$NEW_PREFIX" "$kind"; done
  for kind in "${LEGACY_KINDS[@]}"; do label_for "$LEGACY_PREFIX" "$kind"; done
}

bootout_label() {
  "$LAUNCHCTL" bootout "$DOMAIN/$1" >/dev/null 2>&1 || true
}

atomic_pointer() {
  local value="$1" target="$2" temporary
  mkdir -p "$(dirname "$target")"
  temporary="$(dirname "$target")/.${target##*/}.$$"
  printf '%s\n' "$value" > "$temporary"
  mv -f "$temporary" "$target"
}

persist_config_pointer() {
  atomic_pointer "$DREAMING_CONFIG_FILE" "$DREAMING_CONFIG_POINTER"
}

activate_halt() {
  mkdir -p "$STATE_DIR/skill-review" "$STATE_DIR/dreaming"
  touch "$HALT_SWITCH"
}

cmd_prepare() {
  local label source backup stamp copied=0
  mkdir -p "$DEST_DIR" "$STATE_DIR/dreaming/migration-backups"
  activate_halt

  if [[ -f "$ACTIVE_PREPARE_FILE" ]] &&
      backup="$(<"$ACTIVE_PREPARE_FILE")" &&
      [[ -d "$backup" && -f "$backup/.dreaming-backup-complete" ]]; then
    :
  else
    stamp="$(date -u +%Y%m%dT%H%M%SZ)-$$"
    backup="$STATE_DIR/dreaming/migration-backups/$stamp"
    mkdir -p "$backup"
    while IFS= read -r label; do
      source="$DEST_DIR/$label.plist"
      if [[ -f "$source" ]]; then
        cp -p "$source" "$backup/"
        copied=$((copied + 1))
      fi
    done < <(all_labels | awk '!seen[$0]++')
    printf '%s\n' "$copied" > "$backup/.plist-count"
    touch "$backup/.dreaming-backup-complete"
    atomic_pointer "$backup" "$BACKUP_POINTER"
    atomic_pointer "$backup" "$ACTIVE_PREPARE_FILE"
  fi

  while IFS= read -r label; do
    bootout_label "$label"
  done < <(all_labels | awk '!seen[$0]++')
  echo "prepared migration behind halt; rollback backup: $backup"
}

load_config() {
  local config_file="$DREAMING_CONFIG_FILE"
  [[ -f "$config_file" ]] || {
    echo "dependency config missing: $config_file" >&2
    return 1
  }
  # Generated by dreaming-deps.py using shell-quoted scalar assignments.
  # shellcheck disable=SC1090
  source "$config_file"
  DREAMING_CONFIG_FILE="$config_file"
  export_runtime_env
}

persist_runtime_config_values() {
  /usr/bin/python3 - "$DREAMING_CONFIG_FILE" "$DREAMING_DEPS_DIR" \
    "$DREAMING_CONFIG_FILE" <<'PY'
import os
import shlex
import sys
import uuid
from pathlib import Path

path = Path(sys.argv[1])
updates = {
    "DREAMING_DEPS_DIR": sys.argv[2],
    "DREAMING_CONFIG_FILE": sys.argv[3],
}
lines = [
    line
    for line in path.read_text(encoding="utf-8").splitlines()
    if line.partition("=")[0] not in updates
]
lines.extend(f"{name}={shlex.quote(value)}" for name, value in updates.items())
temporary = path.parent / f".{path.name}.{uuid.uuid4().hex}"
temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
os.chmod(temporary, 0o600)
os.replace(temporary, path)
PY
}

ensure_neutral_roots() {
  mkdir -p "$DREAMING_DATA_DIR" "$DREAMING_STATE_DIR/daemon-logs" \
    "$DREAMING_SKILLS_ROOT"
  if [[ ! -d "$DREAMING_SKILLS_ROOT/.git" ]]; then
    git -C "$DREAMING_SKILLS_ROOT" init -q
  fi
  if [[ -n "$(git -C "$DREAMING_SKILLS_ROOT" remote 2>/dev/null)" ]]; then
    echo "Dreaming canonical skills root must not have a git remote: $DREAMING_SKILLS_ROOT" >&2
    return 1
  fi
}

ensure_dashboard_token() {
  mkdir -p "$(dirname "$DASHBOARD_TOKEN_FILE")" "$HOME/Library/Logs/Dreaming"
  chmod 700 "$(dirname "$DASHBOARD_TOKEN_FILE")"
  if [[ -L "$DASHBOARD_TOKEN_FILE" ]]; then
    echo "dashboard token must not be a symlink: $DASHBOARD_TOKEN_FILE" >&2
    return 1
  fi
  if [[ ! -e "$DASHBOARD_TOKEN_FILE" ]]; then
    /usr/bin/python3 - "$DASHBOARD_TOKEN_FILE" <<'PY'
import os
import secrets
import sys
from pathlib import Path

path = Path(sys.argv[1])
temporary = path.parent / f".{path.name}.{os.getpid()}"
temporary.write_text(secrets.token_urlsafe(32) + "\n", encoding="ascii")
os.chmod(temporary, 0o600)
os.replace(temporary, path)
PY
  fi
  /usr/bin/python3 - "$DASHBOARD_TOKEN_FILE" <<'PY'
import os
import re
import stat
import sys
from pathlib import Path

path = Path(sys.argv[1])
info = path.stat()
if not stat.S_ISREG(info.st_mode) or stat.S_IMODE(info.st_mode) != 0o600:
    raise SystemExit("dashboard token must be a mode-0600 regular file")
if not re.fullmatch(r"[A-Za-z0-9_-]{43}\n?", path.read_text(encoding="ascii")):
    raise SystemExit("dashboard token is malformed")
PY
}

render() {
  local kind="$1" label destination template
  label="$(label_for "$NEW_PREFIX" "$kind")"
  template="$DREAMING_REPO_ROOT/skills/skill-review/assets/launchd/$kind.plist.tpl"
  destination="$DEST_DIR/$label.plist"
  /usr/bin/python3 - "$template" "$destination" "$label" "$HOME" \
    "$DREAMING_REPO_ROOT" "$DREAMING_SHARED_SKILLS_ROOT" \
    "${SKILLS_REPO_ROOT:-}" "$STATE_DIR" "$LOCAL_ROOT" "$COPILOT_ROOT" \
    "$DREAMING_DATA_DIR" "$DREAMING_STATE_DIR" "$DREAMING_SKILLS_ROOT" \
    "$DREAMING_ADAPTER_CONFIG" "$DREAMING_ENABLE_COPILOT_COMPAT" \
    "$DREAMING_ORCHESTRATOR_STATE_DIR" "$DREAMING_RECEIPT_FILE" \
    "$DREAMING_DASHBOARD_HOST" "$DREAMING_DASHBOARD_PORT" \
    "$DASHBOARD_TOKEN_FILE" "$DASHBOARD_ASSETS" <<'PY'
import html
import sys

(
    template,
    destination,
    label,
    home,
    repo,
    shared,
    public,
    state,
    local,
    copilot_home,
    data,
    dreaming_state,
    dreaming_skills,
    adapter_config,
    copilot_compat,
    orchestrator_state,
    receipt_file,
    dashboard_host,
    dashboard_port,
    dashboard_token_file,
    dashboard_assets,
) = sys.argv[1:]
text = open(template, encoding="utf-8").read()
replacements = {
    "__LABEL__": label,
    "__HOME__": home,
    "__DREAMING_REPO_ROOT__": repo,
    "__DREAMING_SHARED_SKILLS_ROOT__": shared,
    "__SKILLS_STATE_DIR__": state,
    "__SKILLS_LOCAL_ROOT__": local,
    "__COPILOT_HOME__": copilot_home,
    "__DREAMING_DATA_DIR__": data,
    "__DREAMING_STATE_DIR__": dreaming_state,
    "__DREAMING_SKILLS_ROOT__": dreaming_skills,
    "__DREAMING_ENABLE_COPILOT_COMPAT__": copilot_compat,
    "__DREAMING_ORCHESTRATOR_STATE_DIR__": orchestrator_state,
    "__DREAMING_RECEIPT_FILE__": receipt_file,
    "__DREAMING_DASHBOARD_HOST__": dashboard_host,
    "__DREAMING_DASHBOARD_PORT__": dashboard_port,
    "__DREAMING_DASHBOARD_TOKEN_FILE__": dashboard_token_file,
    "__DREAMING_DASHBOARD_ASSETS__": dashboard_assets,
}
for key, value in replacements.items():
    text = text.replace(key, html.escape(value))
public_env = ""
if public:
    public_env = (
        "    <key>SKILLS_REPO_ROOT</key><string>"
        + html.escape(public)
        + "</string>\n"
    )
text = text.replace("__SKILLS_REPO_ROOT_ENV__", public_env)
adapter_env = ""
if adapter_config:
    adapter_env = (
        "    <key>DREAMING_ADAPTER_CONFIG</key><string>"
        + html.escape(adapter_config)
        + "</string>\n"
    )
text = text.replace("__DREAMING_ADAPTER_CONFIG_ENV__", adapter_env)
copilot_env = ""
if copilot_compat == "1":
    copilot_env = (
        "    <key>COPILOT_HOME</key><string>"
        + html.escape(copilot_home)
        + "</string>\n"
    )
text = text.replace("__COPILOT_HOME_ENV__", copilot_env)
with open(destination, "w", encoding="utf-8") as handle:
    handle.write(text)
PY
  /usr/bin/plutil -lint "$destination" >/dev/null
}

sync_plugin() {
  [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]] || return 0
  [[ "${DREAMING_SKIP_PLUGIN_SYNC:-0}" == "1" ]] && return 0
  [[ -x "$COPILOT" ]] || {
    echo "copilot is not executable at $COPILOT" >&2
    return 1
  }
  "$COPILOT" plugin update dfrysinger-dreaming >/dev/null 2>&1 ||
    "$COPILOT" plugin install dfrysinger/dreaming
}

configure_native_adapters() {
  local generated="$DREAMING_STATE_DIR/adapters.json"
  if [[ -n "$REQUESTED_ADAPTER_CONFIG" ]]; then
    return 0
  fi
  if [[ "$REQUESTED_ADAPTER_DESIRED_STATE" == "1" ]]; then
    DREAMING_ADAPTER_CONFIG="$generated"
  elif [[ -n "$DREAMING_ADAPTER_CONFIG" ]]; then
    return 0
  elif [[ "$REQUESTED_NATIVE_ADAPTERS" == "1" ||
          "$DREAMING_ENABLE_COPILOT_COMPAT" == "0" ]]; then
    DREAMING_ADAPTER_CONFIG="$generated"
  else
    return 0
  fi
  export_runtime_env
  "$DREAMING_REPO_ROOT/scripts/configure-adapters.py" \
    --output "$DREAMING_ADAPTER_CONFIG" \
    --repo-root "$DREAMING_REPO_ROOT" \
    --state-dir "$DREAMING_STATE_DIR" >/dev/null
}

run_core() {
  export_runtime_env
  "$DREAMING_REPO_ROOT/skills/skill-review/scripts/dreaming-core.py" "$@"
}

PUBLICATION_RESIDUAL=0
attempt_unpublish() {
  local output
  [[ -n "$DREAMING_ADAPTER_CONFIG" &&
     -f "$DREAMING_ADAPTER_CONFIG" ]] || return 0
  if output="$(run_core unpublish 2>&1)"; then
    return 0
  fi
  PUBLICATION_RESIDUAL=1
  echo "warning: publication cleanup incomplete; residual registrations may remain" >&2
  printf '%s\n' "$output" >&2
  return 0
}

cmd_install() {
  local kind label generation
  cmd_prepare
  if [[ "$REQUESTED_COPILOT_MIGRATION" == "1" ]]; then
    "$DREAMING_REPO_ROOT/scripts/migrate-copilot-state.py" apply \
      --legacy-skills "${DREAMING_LEGACY_COPILOT_SKILLS:-$HOME/.copilot/skills}" \
      --legacy-state "${DREAMING_LEGACY_COPILOT_STATE:-$HOME/.copilot/skill-state/skill-review}" \
      --target-skills "$DREAMING_SKILLS_ROOT" \
      --target-state "$DREAMING_STATE_DIR" \
      --journal "$DREAMING_STATE_DIR/copilot-migration.json" >/dev/null
  fi
  configure_native_adapters
  DREAMING_REPO_ROOT="$DREAMING_REPO_ROOT" \
    DREAMING_DATA_DIR="$DREAMING_DATA_DIR" \
    DREAMING_STATE_DIR="$DREAMING_STATE_DIR" \
    DREAMING_SKILLS_ROOT="$DREAMING_SKILLS_ROOT" \
    DREAMING_ADAPTER_CONFIG="$DREAMING_ADAPTER_CONFIG" \
    DREAMING_ENABLE_COPILOT_COMPAT="$DREAMING_ENABLE_COPILOT_COMPAT" \
    DREAMING_DEPS_DIR="$DREAMING_DEPS_DIR" \
    DREAMING_CONFIG_FILE="$DREAMING_CONFIG_FILE" \
    "$DREAMING_REPO_ROOT/scripts/dreaming-deps.py" materialize
  persist_runtime_config_values
  load_config
  persist_config_pointer
  ensure_neutral_roots
  ensure_dashboard_token
  sync_plugin
  chmod +x "$DREAMING_REPO_ROOT/scripts/"*.sh \
    "$DREAMING_REPO_ROOT/scripts/"*.py \
    "$DREAMING_REPO_ROOT"/skills/*/scripts/*.sh \
    "$DREAMING_REPO_ROOT"/skills/*/scripts/*.py 2>/dev/null || true
  if [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
    "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" install
  fi

  for kind in "${LEGACY_KINDS[@]}"; do
    label="$(label_for "$LEGACY_PREFIX" "$kind")"
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done
  for kind in "${NEW_KINDS[@]}"; do
    label="$(label_for "$NEW_PREFIX" "$kind")"
    render "$kind"
    "$LAUNCHCTL" bootstrap "$DOMAIN" "$DEST_DIR/$label.plist"
    "$LAUNCHCTL" enable "$DOMAIN/$label" >/dev/null 2>&1 || true
    echo "loaded $label"
  done
  generation="$(date -u +%Y%m%dT%H%M%SZ)-install-$$"
  atomic_pointer "$generation" "$GENERATION_FILE"
  atomic_pointer "$(label_for "$NEW_PREFIX" selftest)" "$SELFTEST_LABEL_FILE"
  rm -f "$SELFTEST_GENERATION_FILE"
  echo "installed ${#NEW_KINDS[@]} agents; halt remains active until selftest and enable"
}

cmd_selftest() {
  local label result wait_secs waited generation expected_generation
  [[ -f "$SELFTEST_LABEL_FILE" ]] || {
    echo "no active selftest label; run install or rollback first" >&2
    return 1
  }
  label="$(<"$SELFTEST_LABEL_FILE")"
  result="${DREAMING_SELFTEST_RESULT_FILE:-$STATE_DIR/daemon-selftest.out}"
  wait_secs="${DREAMING_SELFTEST_WAIT_SECS:-3600}"
  [[ -f "$GENERATION_FILE" ]] || {
    echo "no activation generation; run install or rollback first" >&2
    return 1
  }
  expected_generation="$(<"$GENERATION_FILE")"
  rm -f "$result"
  "$LAUNCHCTL" kickstart -k "$DOMAIN/$label" >/dev/null 2>&1 || {
    echo "selftest agent not loaded; run install first" >&2
    return 1
  }
  waited=0
  while (( waited < wait_secs )); do
    if [[ -f "$result" ]] && grep -q '^== result: [0-9][0-9]* failure(s) ==$' "$result"; then
      break
    fi
    sleep 1
    waited=$((waited + 1))
  done
  [[ -f "$result" ]] || { echo "selftest produced no result file" >&2; return 1; }
  cat "$result"
  grep -q '^== result: 0 failure(s) ==$' "$result" || {
    echo "selftest did not pass" >&2
    return 1
  }
  generation="$(<"$GENERATION_FILE")"
  [[ "$generation" == "$expected_generation" ]] || {
    echo "activation generation changed while selftest was running" >&2
    return 1
  }
  dashboard_health_check
  atomic_pointer "$expected_generation" "$SELFTEST_GENERATION_FILE"
  echo "selftest passed for activation generation $expected_generation"
}

dashboard_health_check() {
  [[ "${DREAMING_SKIP_DASHBOARD_HEALTH_CHECK:-0}" == "1" ]] && return 0
  [[ -f "$DEST_DIR/$(label_for "$NEW_PREFIX" dashboard).plist" ]] || return 0
  /usr/bin/python3 - "$DREAMING_DASHBOARD_HOST" "$DREAMING_DASHBOARD_PORT" \
    "$DASHBOARD_TOKEN_FILE" "${DREAMING_DASHBOARD_HEALTH_WAIT_SECS:-60}" \
    "$expected_generation" <<'PY'
import json
import sys
import time
import urllib.request

host, port, token_file, wait_seconds, expected_generation = sys.argv[1:]
token = open(token_file, encoding="ascii").read().strip()
deadline = time.monotonic() + float(wait_seconds)
while True:
    request = urllib.request.Request(
        f"http://{host}:{port}/api/v1/health",
        headers={"Authorization": f"Bearer {token}"},
    )
    try:
        with urllib.request.urlopen(request, timeout=5) as response:
            payload = json.load(response)
        break
    except OSError:
        if time.monotonic() >= deadline:
            raise
        time.sleep(0.5)
if (
    payload.get("schema_version") != 1
    or not isinstance(payload.get("data"), dict)
    or payload["data"].get("activation_generation") != expected_generation
):
    raise SystemExit("dashboard health response is invalid")
PY
}

cmd_enable() {
  local generation passed
  [[ -f "$GENERATION_FILE" && -f "$SELFTEST_GENERATION_FILE" ]] || {
    echo "current activation has not passed selftest" >&2
    return 1
  }
  generation="$(<"$GENERATION_FILE")"
  passed="$(<"$SELFTEST_GENERATION_FILE")"
  [[ "$generation" == "$passed" ]] || {
    echo "selftest belongs to a different activation generation" >&2
    return 1
  }
  if [[ -n "$DREAMING_ADAPTER_CONFIG" && -f "$DREAMING_ADAPTER_CONFIG" ]]; then
    run_core publish
  fi
  rm -f "$HALT_SWITCH"
  rm -f "$ACTIVE_PREPARE_FILE"
  echo "dreaming enabled"
}

cmd_status() {
  local label
  echo "halt=$([[ -e "$HALT_SWITCH" ]] && echo active || echo inactive)"
  [[ -f "$BACKUP_POINTER" ]] && echo "rollback_backup=$(<"$BACKUP_POINTER")"
  [[ -f "$GENERATION_FILE" ]] && echo "activation_generation=$(<"$GENERATION_FILE")"
  echo "data_root=$DREAMING_DATA_DIR"
  echo "state_root=$DREAMING_STATE_DIR"
  echo "skills_root=$DREAMING_SKILLS_ROOT"
  echo "copilot_compat=$DREAMING_ENABLE_COPILOT_COMPAT"
  echo "dashboard_url=http://$DREAMING_DASHBOARD_HOST:$DREAMING_DASHBOARD_PORT/"
  echo "dashboard_token=$([[ -f "$DASHBOARD_TOKEN_FILE" ]] && echo ready || echo missing)"
  [[ -n "$DREAMING_ADAPTER_CONFIG" ]] &&
    echo "adapter_config=$DREAMING_ADAPTER_CONFIG"
  if [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
    "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" status || true
  fi
  while IFS= read -r label; do
    echo "--- $label ---"
    "$LAUNCHCTL" print "$DOMAIN/$label" 2>/dev/null |
      grep -E 'state|runs|last exit|program =' || echo "  (not loaded)"
  done < <(all_labels | awk '!seen[$0]++')
}

cmd_dashboard_url() {
  ensure_dashboard_token
  printf 'http://%s:%s/#access_token=%s\n' \
    "$DREAMING_DASHBOARD_HOST" "$DREAMING_DASHBOARD_PORT" \
    "$(<"$DASHBOARD_TOKEN_FILE")"
}

cmd_dashboard_open() {
  local url
  url="$(cmd_dashboard_url)"
  "${DREAMING_OPEN_BIN:-/usr/bin/open}" "$url"
}

cmd_uninstall() {
  local label
  cmd_prepare
  attempt_unpublish
  while IFS= read -r label; do
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done < <(all_labels | awk '!seen[$0]++')
  rm -f "$GENERATION_FILE" "$SELFTEST_GENERATION_FILE" "$SELFTEST_LABEL_FILE"
  if [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
    "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" uninstall
  fi
  if [[ -f "$DREAMING_CONFIG_POINTER" &&
        "$(<"$DREAMING_CONFIG_POINTER")" == "$DREAMING_CONFIG_FILE" ]]; then
    rm -f "$DREAMING_CONFIG_POINTER"
  fi
  if [[ "$PUBLICATION_RESIDUAL" == "1" ]]; then
    echo "uninstalled all known dreaming and legacy agents; publication residuals remain; halt remains active"
  else
    echo "uninstalled all known dreaming and legacy agents; halt remains active"
  fi
}

verify_backup() {
  /usr/bin/python3 - "$1" <<'PY'
import os
import plistlib
import sys
from pathlib import Path

backup = Path(sys.argv[1])
plists = sorted(backup.glob("*.plist"))
if not plists:
    raise SystemExit("backup contains no LaunchAgent plists")
failures = []
for plist in plists:
    try:
        data = plistlib.loads(plist.read_bytes())
    except Exception as exc:
        failures.append(f"{plist.name}: malformed plist: {exc}")
        continue
    arguments = data.get("ProgramArguments")
    if not isinstance(arguments, list) or not arguments or not all(
        isinstance(value, str) for value in arguments
    ):
        failures.append(f"{plist.name}: ProgramArguments must be a non-empty string array")
        continue
    for index, raw in enumerate(arguments):
        path = Path(os.path.expanduser(raw))
        if not path.is_absolute():
            continue
        must_execute = index == 0 or path.suffix in {".sh", ".py"} or os.access(path, os.X_OK)
        if must_execute and not (path.is_file() and os.access(path, os.X_OK)):
            failures.append(f"{plist.name}: executable missing or not executable: {path}")
        elif not must_execute and not path.exists():
            failures.append(f"{plist.name}: durable argument path is missing: {path}")
if failures:
    raise SystemExit("\n".join(failures))
PY
}

cmd_rollback() {
  local backup="${1:-}" label plist generation lock_path selftest_plist
  activate_halt
  if [[ -z "$backup" ]]; then
    [[ -f "$BACKUP_POINTER" ]] || {
      echo "no migration backup recorded" >&2
      return 1
    }
    backup="$(<"$BACKUP_POINTER")"
  fi
  [[ -d "$backup" && -f "$backup/.dreaming-backup-complete" ]] || {
    echo "invalid migration backup: $backup" >&2
    return 1
  }
  verify_backup "$backup"
  selftest_plist="$(find "$backup" -maxdepth 1 -type f -name '*.selftest.plist' -print)"
  [[ -n "$selftest_plist" && "$(printf '%s\n' "$selftest_plist" | wc -l | tr -d ' ')" == "1" ]] || {
    echo "rollback backup must contain exactly one selftest LaunchAgent" >&2
    return 1
  }
  attempt_unpublish

  while IFS= read -r label; do
    bootout_label "$label"
    rm -f "$DEST_DIR/$label.plist"
  done < <(all_labels | awk '!seen[$0]++')
  if [[ "$DREAMING_ENABLE_COPILOT_COMPAT" == "1" ]]; then
    "$DREAMING_REPO_ROOT/scripts/manage-instructions.sh" uninstall
  fi
  lock_path="$STATE_DIR/daemon.lock"
  if [[ -f "$lock_path" ]]; then
    mv "$lock_path" "$STATE_DIR/dreaming/daemon.lock.sqlite-before-rollback"
    [[ -f "${lock_path}-wal" ]] &&
      mv "${lock_path}-wal" "$STATE_DIR/dreaming/daemon.lock.sqlite-wal-before-rollback"
    [[ -f "${lock_path}-shm" ]] &&
      mv "${lock_path}-shm" "$STATE_DIR/dreaming/daemon.lock.sqlite-shm-before-rollback"
  fi
  for plist in "$backup"/*.plist; do
    [[ -e "$plist" ]] || continue
    cp -p "$plist" "$DEST_DIR/"
    label="$(basename "$plist" .plist)"
    "$LAUNCHCTL" bootstrap "$DOMAIN" "$DEST_DIR/$label.plist"
    "$LAUNCHCTL" enable "$DOMAIN/$label" >/dev/null 2>&1 || true
    echo "restored $label"
  done
  generation="$(date -u +%Y%m%dT%H%M%SZ)-rollback-$$"
  atomic_pointer "$generation" "$GENERATION_FILE"
  atomic_pointer "$(basename "$selftest_plist" .plist)" "$SELFTEST_LABEL_FILE"
  rm -f "$SELFTEST_GENERATION_FILE"
  if [[ "$PUBLICATION_RESIDUAL" == "1" ]]; then
    echo "rollback loaded behind halt from $backup; publication residuals remain; run restored selftest, then enable explicitly"
  else
    echo "rollback loaded behind halt from $backup; run restored selftest, then enable explicitly"
  fi
}

cmd_rollback_migration() {
  local journal="$DREAMING_STATE_DIR/copilot-migration.json"
  activate_halt
  [[ -f "$journal" ]] || {
    echo "no Copilot migration journal recorded: $journal" >&2
    return 1
  }
  "$DREAMING_REPO_ROOT/scripts/migrate-copilot-state.py" rollback \
    --legacy-skills "${DREAMING_LEGACY_COPILOT_SKILLS:-$HOME/.copilot/skills}" \
    --legacy-state "${DREAMING_LEGACY_COPILOT_STATE:-$HOME/.copilot/skill-state/skill-review}" \
    --target-skills "$DREAMING_SKILLS_ROOT" \
    --target-state "$DREAMING_STATE_DIR" \
    --journal "$journal"
  echo "migration data rolled back; halt remains active"
}

run_with_lifecycle_lock() {
  mkdir -p "$(dirname "$LIFECYCLE_LOCK_FILE")"
  exec /usr/bin/python3 - "$LIFECYCLE_LOCK_FILE" "$0" "$@" <<'PY'
import fcntl
import os
import subprocess
import sys

lock_path, script, *args = sys.argv[1:]
with open(lock_path, "a+") as lock:
    os.chmod(lock_path, 0o600)
    fcntl.flock(lock, fcntl.LOCK_EX)
    env = os.environ.copy()
    env["DREAMING_LIFECYCLE_LOCK_HELD"] = "1"
    raise SystemExit(subprocess.run([script, *args], env=env).returncode)
PY
}

if [[ "${DREAMING_LIFECYCLE_LOCK_HELD:-0}" != "1" ]]; then
  case "${1:-}" in
    prepare|install|selftest|enable|uninstall|rollback|rollback-migration)
      run_with_lifecycle_lock "$@"
      ;;
  esac
fi

case "${1:-}" in
  prepare) cmd_prepare ;;
  install) cmd_install ;;
  selftest) cmd_selftest ;;
  enable) cmd_enable ;;
  status) cmd_status ;;
  dashboard-url) cmd_dashboard_url ;;
  dashboard-open) cmd_dashboard_open ;;
  uninstall) cmd_uninstall ;;
  rollback) shift; cmd_rollback "${1:-}" ;;
  rollback-migration) cmd_rollback_migration ;;
  *)
    echo "usage: scripts/install.sh {prepare|install|selftest|enable|status|dashboard-url|dashboard-open|uninstall|rollback [backup]|rollback-migration}" >&2
    exit 2
    ;;
esac
